version: '3'
services:
  ai-llm-matrix-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: matrix-bot
    volumes:
      - ./nio_store:/app/nio_store
      - ./config:/app/config
      - ./private.pem:/app/private.pem
      - ./public.pem:/app/public.pem
    environment:
      - CONFIG_PATH=/app/config/config.json
    networks:
      - xwiki-nw
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

networks:
  xwiki-nw:
    external: true
