version: '2'
networks:
  bridge:
    driver: bridge
services:
  ai-llm-matrix-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: matrix-bot
    environment:
      - CONFIG_PATH=/app/config/config.json
    volumes:
      - ./nio_store:/app/nio_store
      - ./config:/app/config
      - ./private.pem:/app/private.pem
      - ./public.pem:/app/public.pem
    networks:
      - bridge
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"